refresh_rate = "5 seconds"

[appenders.stdout]
kind = "console"

    [appenders.stdout.encoder]
    pattern = "{d(%+)(utc)} [{f}:{L}] {h({l})} {M}:{m}{n}"

    [[appenders.stdout.filters]]
    kind = "threshold"
    level = "info"

[appenders.file]
kind = "file"
path = "log/file.log"

    [appenders.file.encoder]
    pattern = "[{d(%Y-%m-%dT%H:%M:%S%.6f)} {h({l}):<5.5} {M}] {m}{n}"

[appenders.rollingfile]
kind = "rolling_file"
path = "log/rolling_file.log"

    [appenders.rollingfile.encoder]
    pattern = "[{d(%Y-%m-%dT%H:%M:%S%.6f)} {h({l}):<5.5} {M}] {m}{n}"

[appenders.rollingfile.policy.trigger]
kind = "time"
interval = "1 minute"

[appenders.rollingfile.policy.roller]
kind = "fixed_window"
pattern = "log/old-rolling_file-{}.log"
base = 0
count = 2

[root]
level = "info"
appenders = [ "stdout", "file", "rollingfile" ]
