[package]
name = "json_logger"
version = "0.1.0"
authors = ["Calvin Brown <cab025@protonmail.com"]
edition = "2018"

[dependencies]
log = "0.4.8"
log4rs = {version = "0.8.3", features = ["json_encoder"]}
