---
name: EditorConfig Checker

on:
  push:
    branches:
    - main
    - devel
  pull_request:
    branches:
    - main
    - devel

jobs:
  editorconfig:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: editorconfig-checker/action-editorconfig-checker@main
    - run: editorconfig-checker
